# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1107, 530)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 29, 1091, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.dockWidget = QtWidgets.QDockWidget(self.gridLayoutWidget)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.dockWidgetContents)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(180, 20, 841, 371))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Screen_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Screen_1.setFrameShape(QtWidgets.QFrame.Box)
        self.Screen_1.setText("")
        self.Screen_1.setObjectName("Screen_1")
        self.horizontalLayout.addWidget(self.Screen_1)
        self.Screen_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Screen_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.Screen_2.setText("")
        self.Screen_2.setObjectName("Screen_2")
        self.horizontalLayout.addWidget(self.Screen_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.dockWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 160, 450))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Load = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Load.setObjectName("Load")
        self.verticalLayout.addWidget(self.Load)
        self.Load_Video = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Load_Video.setObjectName("Load_Video")
        self.verticalLayout.addWidget(self.Load_Video)
        self.Open_camera = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Open_camera.setObjectName("Open_camera")
        self.verticalLayout.addWidget(self.Open_camera)
        self.Gray_scale = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Gray_scale.setObjectName("Gray_scale")
        self.verticalLayout.addWidget(self.Gray_scale)
        self.Mean = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Mean.setObjectName("Mean")
        self.verticalLayout.addWidget(self.Mean)
        self.Median = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Median.setObjectName("Median")
        self.verticalLayout.addWidget(self.Median)
        self.Gauss = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Gauss.setObjectName("Gauss")
        self.verticalLayout.addWidget(self.Gauss)
        self.Bilateral = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Bilateral.setObjectName("Bilateral")
        self.verticalLayout.addWidget(self.Bilateral)
        self.Erosion = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Erosion.setObjectName("Erosion")
        self.verticalLayout.addWidget(self.Erosion)
        self.Dilation = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Dilation.setObjectName("Dilation")
        self.verticalLayout.addWidget(self.Dilation)
        self.Closing = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Closing.setObjectName("Closing")
        self.verticalLayout.addWidget(self.Closing)
        self.Opening = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Opening.setObjectName("Opening")
        self.verticalLayout.addWidget(self.Opening)
        self.Clear = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Clear.setObjectName("Clear")
        self.verticalLayout.addWidget(self.Clear)
        self.usedcommand = QtWidgets.QLabel(self.dockWidgetContents)
        self.usedcommand.setGeometry(QtCore.QRect(180, 395, 841, 61))
        self.usedcommand.setAutoFillBackground(True)
        self.usedcommand.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.usedcommand.setFrameShadow(QtWidgets.QFrame.Plain)
        self.usedcommand.setLineWidth(3)
        self.usedcommand.setText("")
        self.usedcommand.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.usedcommand.setObjectName("usedcommand")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setGeometry(QtCore.QRect(340, 0, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(780, 0, 55, 16))
        self.label_2.setObjectName("label_2")
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.gridLayout.addWidget(self.dockWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Load.setText(_translate("Form", "Load"))
        self.Load_Video.setText(_translate("Form", "Load_Video"))
        self.Open_camera.setText(_translate("Form", "Open_camera"))
        self.Gray_scale.setText(_translate("Form", "Gray_scale"))
        self.Mean.setText(_translate("Form", "Mean"))
        self.Median.setText(_translate("Form", "Median"))
        self.Gauss.setText(_translate("Form", "Gaus_blur"))
        self.Bilateral.setText(_translate("Form", "Bilateral"))
        self.Erosion.setText(_translate("Form", "Erosion"))
        self.Dilation.setText(_translate("Form", "Dilation"))
        self.Closing.setText(_translate("Form", "Closing"))
        self.Opening.setText(_translate("Form", "Opening"))
        self.Clear.setText(_translate("Form", "Clear"))
        self.label.setText(_translate("Form", "Processed"))
        self.label_2.setText(_translate("Form", "Original"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
